### ISSUE TITLE
Missing route to remove contact from blacklist

### ISSUE THREAD

**Issue by Gwemox** [smsfactor/smsfactor-php-sdk#4]
Hello,

Your support provided me the `DELETE /blacklist/contact/{id}` route, however it seems to be missing from this SDK.

**Comment by fpalamour** [comment]
Indeed it is missing from the SDK, although I think this endpoint should be duplicated into a version that would take a destination instead of an ID. I believe it would be way more convenient for developers. Or, if we document this endpoint for it to be used by developers, we should at least provide a better way to fetch a blacklist contact ID instead of getting the whole blacklist and then looping over it, which is really  unefficient.

**Comment by fpalamour** [comment]
I added the function on the master branch. Are you able to use the master version with composer or do you prefer to have a new release ?

**Comment by Gwemox** [comment]
Release is better

**Comment by fpalamour** [comment]
La version 1.0.4 est disponible.
